apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: k8spratices-validation-webhook
webhooks:
- name: k8spratices-webhook.armateur.svc
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - services
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: armateur
      name: k8spratices-webhook
      path: /services
      port: 443
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURwakNDQW82Z0F3SUJBZ0lVZEdnREZSc2lEVjNJejUrdXRSbjMvTUF6VFBVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2F6RUxNQWtHQTFVRUJoTUNWVk14RHpBTkJnTlZCQWdUQms5eVpXZHZiakVSTUE4R0ExVUVCeE1JVUc5eQpkR3hoYm1ReEV6QVJCZ05WQkFvVENrdDFZbVZ5Ym1WMFpYTXhDekFKQmdOVkJBc1RBa05CTVJZd0ZBWURWUVFECkV3MUxkV0psY201bGRHVnpJRU5CTUI0WERURTVNRGt4TnpFek5ETXdNRm9YRFRJME1Ea3hOVEV6TkRNd01Gb3cKYXpFTE1Ba0dBMVVFQmhNQ1ZWTXhEekFOQmdOVkJBZ1RCazl5WldkdmJqRVJNQThHQTFVRUJ4TUlVRzl5ZEd4aApibVF4RXpBUkJnTlZCQW9UQ2t0MVltVnlibVYwWlhNeEN6QUpCZ05WQkFzVEFrTkJNUll3RkFZRFZRUURFdzFMCmRXSmxjbTVsZEdWeklFTkJNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXlxNy8KY1NsU0N4Ty9kQi9lRUVDUFR4S2VvcVpXM1RwV0p4b3Z0a3BCTldoYm9TUXhxVC8xK1NlVDRQaC91eUhLd2pSVwpYRldmYkxncDcwQmhqLytRZVpkbnBmQ0cxelVJbThPWTcvZERiSk1Qa1l1UWpqQUsrNDlmMHllYXVzK0VRVE8vClZmTExlSUVIQ2ZydVd1MWM4S2ZEdjhwbFRVL1JqTWExS1Z1SDZsaWVMWjBsTlZRR01hUTdmSFRjNENFbk5kVmcKazFmdWFRZFQreTFMVnkxU25hWkFqRFBhc0hXT1RpNTNzdlBMOVZrOVJDMVJXWWJZK0pZWURqQmlaVkF3S3kvNAo5QzVxUGR0SW5rVHZFZE5vTTBWLzFiM0tVRGVoY0lrT0h6Q09pcHIrMndzbUNzMmJ6UVNpYldHc3pnSk9ZdTNLClozYXhQcXlyU0xyWTBaV3Vjd0lEQVFBQm8wSXdRREFPQmdOVkhROEJBZjhFQkFNQ0FRWXdEd1lEVlIwVEFRSC8KQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVTnFhcm10M0ZLVHc1THMxcEgxNDhuM2JZVXhjd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBQTFyMUM3SXlKemFENk1mU21DSG92OUk3dTl6eDdXU0xINncrN1hVMGd3TTNHWE5MTThyCmZDYU5pWlg5SDljZ0tqRDNpVjhiRVRBRVFwa3l0T0tHMElaQzlKc0RKOHpHamNGd2o3UURmRHFLckJ5d3NOTFIKalorRS9HNlF0clZlUSt4d0ZsYUJiV1F0dThBZU1hckF5S0hpQ3UyZzllQ3dKQzJoUHhGbTEzRUpBTkl0TlBVUgp2Z1cxSklGZWFaN3h1c3hEdU9qdlJWNDRWL0c3VzNzTkpSeWlQcjQ5cGIzNGtXZ1pyOGVidWNMWG91R1lsb0I2Cmo3NXVyK1lPU0MwN0FJL25uRHpzcm9yRXFnU1JEcndUaDRMQWFlV2h1N1VPRTd5MHdtdzk3VllCYndBcmFMR0YKUzdIbnNnZ3ZGQkFQOVlqdUQ5NEF5VWs4Z252UzhUQVgvZHc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
- name: k8spratices-webhook.armateur.svc
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    - deployments
    - daemonsets
    - replicasets
    - statefulsets
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: armateur
      name: k8spratices-webhook
      path: /workloads
      port: 443
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURwakNDQW82Z0F3SUJBZ0lVZEdnREZSc2lEVjNJejUrdXRSbjMvTUF6VFBVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2F6RUxNQWtHQTFVRUJoTUNWVk14RHpBTkJnTlZCQWdUQms5eVpXZHZiakVSTUE4R0ExVUVCeE1JVUc5eQpkR3hoYm1ReEV6QVJCZ05WQkFvVENrdDFZbVZ5Ym1WMFpYTXhDekFKQmdOVkJBc1RBa05CTVJZd0ZBWURWUVFECkV3MUxkV0psY201bGRHVnpJRU5CTUI0WERURTVNRGt4TnpFek5ETXdNRm9YRFRJME1Ea3hOVEV6TkRNd01Gb3cKYXpFTE1Ba0dBMVVFQmhNQ1ZWTXhEekFOQmdOVkJBZ1RCazl5WldkdmJqRVJNQThHQTFVRUJ4TUlVRzl5ZEd4aApibVF4RXpBUkJnTlZCQW9UQ2t0MVltVnlibVYwWlhNeEN6QUpCZ05WQkFzVEFrTkJNUll3RkFZRFZRUURFdzFMCmRXSmxjbTVsZEdWeklFTkJNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXlxNy8KY1NsU0N4Ty9kQi9lRUVDUFR4S2VvcVpXM1RwV0p4b3Z0a3BCTldoYm9TUXhxVC8xK1NlVDRQaC91eUhLd2pSVwpYRldmYkxncDcwQmhqLytRZVpkbnBmQ0cxelVJbThPWTcvZERiSk1Qa1l1UWpqQUsrNDlmMHllYXVzK0VRVE8vClZmTExlSUVIQ2ZydVd1MWM4S2ZEdjhwbFRVL1JqTWExS1Z1SDZsaWVMWjBsTlZRR01hUTdmSFRjNENFbk5kVmcKazFmdWFRZFQreTFMVnkxU25hWkFqRFBhc0hXT1RpNTNzdlBMOVZrOVJDMVJXWWJZK0pZWURqQmlaVkF3S3kvNAo5QzVxUGR0SW5rVHZFZE5vTTBWLzFiM0tVRGVoY0lrT0h6Q09pcHIrMndzbUNzMmJ6UVNpYldHc3pnSk9ZdTNLClozYXhQcXlyU0xyWTBaV3Vjd0lEQVFBQm8wSXdRREFPQmdOVkhROEJBZjhFQkFNQ0FRWXdEd1lEVlIwVEFRSC8KQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVTnFhcm10M0ZLVHc1THMxcEgxNDhuM2JZVXhjd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBQTFyMUM3SXlKemFENk1mU21DSG92OUk3dTl6eDdXU0xINncrN1hVMGd3TTNHWE5MTThyCmZDYU5pWlg5SDljZ0tqRDNpVjhiRVRBRVFwa3l0T0tHMElaQzlKc0RKOHpHamNGd2o3UURmRHFLckJ5d3NOTFIKalorRS9HNlF0clZlUSt4d0ZsYUJiV1F0dThBZU1hckF5S0hpQ3UyZzllQ3dKQzJoUHhGbTEzRUpBTkl0TlBVUgp2Z1cxSklGZWFaN3h1c3hEdU9qdlJWNDRWL0c3VzNzTkpSeWlQcjQ5cGIzNGtXZ1pyOGVidWNMWG91R1lsb0I2Cmo3NXVyK1lPU0MwN0FJL25uRHpzcm9yRXFnU1JEcndUaDRMQWFlV2h1N1VPRTd5MHdtdzk3VllCYndBcmFMR0YKUzdIbnNnZ3ZGQkFQOVlqdUQ5NEF5VWs4Z252UzhUQVgvZHc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K